### ISSUE TITLE
TypeScript declaration file

### ISSUE THREAD

**Issue by bossqone** [emyann/morphism#11]
Hello, I wanted to use your library but after install I've hit this issue:
```
import Morphism from 'morphism';
```
```
Could not find a declaration file for module 'morphism'. 'C:/project/node_modules/morphism/dist/morphism.js' implicitly has an 'any' type.
Try `npm install @types/morphism` if it exists or add a new declaration (.d.ts) file containing `declare module 'morphism';`
```
I was able to fix this issue with `declare module 'morphism'`, but wouldn't be better solution to provide TypeScript declarations (typings?) directly inside package?

Best regards,
Lukas

**Comment by bossqone** [comment]
any updates? :)

**Comment by emyann** [comment]
Please have a look at #15 #16 :)

**Comment by emyann** [comment]
I close this issue. Should have been fixed with https://github.com/emyann/morphism/releases/tag/v0.6.0
