### ISSUE TITLE
Lodash dependency

### ISSUE THREAD

**Issue by bossqone** [emyann/morphism#15]
Hello,
I've been doing analysis of our Angular bundles and I found out that Morphism brings Lodash dependency. It results in increase of package bundle, because it is pulling whole Lodash package (cca 500KB).

Is it possible to get rid of lodash, or at least optimize it for tree-shaking?

Thanks,
Lukas

**Comment by emyann** [comment]
Hello Lukas! 👋🏽

Thank you for your feedback and indeed you're right! 😬 I have planned to remove lodash dependency, and already started a branch, but didn't get enough time to close it. I'll work on it and release it by the end of the week. 🙏🏽
I might not be able to remove it all but in that case, I'll just pick the functions I need. 

I will let you know here when this has been done,

Thanks!

Yann

**Comment by emyann** [comment]
@bossqone  I have moved the library to `Webpack` and `TypeScript`. The size of the package has dropped to **106KB**
<img width="571" alt="screen shot 2018-01-10 at 3 59 06 am" src="https://user-images.githubusercontent.com/4748419/34763992-0a129856-f5bb-11e7-846c-bd5e280ca7c8.png">

Please have a look a this PR #16 , I also added a `d.ts` file that I will improve in the next days. There're still few useful lodash methods used, I will try to remove them in the future. 

Thanks for your feedback, I will merge this PR tomorrow if it's looks good to you 👍🏽

Yann
